### ISSUE TITLE
Work to change from using HipChatListener to HipChatNotifier#perform has introduced UnsupportedOperationException bug

### ISSUE THREAD

**Issue by KolonelKustard** [jenkinsci/hipchat-plugin#20]
We've noticed that the following commit: a9782d4c82f881012d47690491feaa8c67cf9cef appears to result in failures with the following error message:

```
13:38:10 ERROR: Publisher jenkins.plugins.hipchat.HipChatNotifier aborted due to exception
13:38:10 java.lang.UnsupportedOperationException
13:38:10 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:95)
13:38:10 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:59)
13:38:10 	at jenkins.plugins.hipchat.HipChatNotifier.perform(HipChatNotifier.java:173)
13:38:10 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
13:38:10 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
13:38:10 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:757)
13:38:10 	at hudson.model.Build$BuildExecution.cleanUp(Build.java:192)
13:38:10 	at hudson.model.Run.execute(Run.java:1723)
13:38:10 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
13:38:10 	at hudson.model.ResourceController.execute(ResourceController.java:88)
13:38:10 	at hudson.model.Executor.run(Executor.java:231)
```

**Comment by retoo** [comment]
Fixed with https://github.com/jenkinsci/hipchat-plugin/pull/36
