### ISSUE TITLE
ssl errors

### ISSUE THREAD

**Issue by jillesvangurp** [jenkinsci/hipchat-plugin#27]
since a few days we are getting the error below in our jenkins log and no more messages are going to hipchat:

We run centos 6.x with Jenkins 1.593
openjdk version "1.8.0_25"
OpenJDK Runtime Environment (build 1.8.0_25-b17)
OpenJDK 64-Bit Server VM (build 25.20-b23, mixed mode)

Any ideas on how to fix this? We've updated jenkins and all plugins to their latest versions. 

Dec 11, 2014 6:48:53 PM jenkins.plugins.hipchat.StandardHipChatService publish
WARNING: Error posting to HipChat
javax.net.ssl.SSLException: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: EC AlgorithmParameters not available
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1874)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1857)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1783)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:128)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at org.apache.commons.httpclient.methods.EntityEnclosingMethod.writeRequestBody(EntityEnclosingMethod.java:506)
        at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2114)
        at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
        at jenkins.plugins.hipchat.StandardHipChatService.publish(StandardHipChatService.java:50)
        at jenkins.plugins.hipchat.ActiveNotifier.notifyStart(ActiveNotifier.java:53)
        at jenkins.plugins.hipchat.ActiveNotifier.started(ActiveNotifier.java:46)
        at jenkins.plugins.hipchat.HipChatNotifier$HipChatJobProperty.prebuild(HipChatNotifier.java:203)
        at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:804)
        at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:799)
        at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:795)
        at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:530)
        at hudson.model.Run.execute(Run.java:1759)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
        at hudson.model.ResourceController.execute(ResourceController.java:89)
        at hudson.model.Executor.run(Executor.java:240)
Caused by: java.lang.RuntimeException: java.security.NoSuchAlgorithmException: EC AlgorithmParameters not available
        at sun.security.util.ECUtil.getECParameters(ECUtil.java:141)
        at sun.security.util.ECUtil.getECParameterSpec(ECUtil.java:190)
        at sun.security.ssl.JsseJce.getECParameterSpec(JsseJce.java:385)
        at sun.security.ssl.HandshakeMessage$ECDH_ServerKeyExchange.<init>(HandshakeMessage.java:1060)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:277)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:936)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:871)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:728)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        ... 21 more
Caused by: java.security.NoSuchAlgorithmException: EC AlgorithmParameters not available
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
        at java.security.Security.getImpl(Security.java:695)
        at java.security.AlgorithmParameters.getInstance(AlgorithmParameters.java:146)
        at sun.security.util.ECUtil.getECParameters(ECUtil.java:139)
        ... 31 more

**Comment by paulej** [comment]
jillesvangurp, I was having the exact same problem with another software package.  Your suggestion to use the Java code from  Oracle vs. OpenJDK solved my problem, too.  It seems some of the required crypto ciphers are missing in the OpenJDK package and that affects several software products.

**Comment by aldaris** [comment]
Going to close this as not a defect, since the problem was with OpenJDK and not with the plugin.
